### ISSUE TITLE
What about butch getOrLoad function?

### ISSUE THREAD

**Issue by andrew-papaya** [francescorivola/rabbit-lru-cache#607]
In many cases such as dataLoader you what to be able get large chunks. (500 items) and do it in one query.

**Comment by francescorivola** [comment]
Hi @andrew-papaya ,

I think it could be an interesting feature. Said that it comes with some technical challenges. The current getOrLoad function does not store the data into cache if during the load an invalidation message is consumed. In this way we avoid store into cache stale data from a potential dirty read.
In the case of a bulk load, to ensure no stale data goes into cache, the lib may needs to avoid store into cache if any invalidation comes during loading. In a situation where invalidation frequency is high may make the cache useless. I need to think a bit more deeper on it.

In the meantime, could you please describe your use case for this feature? Are you having a distributed system? How many process are involved, etc..? Is the use case to load items when the process starts?

Thank you

**Comment by francescorivola** [comment]
Hi @andrew-papaya,

I finally going to close this feature request as won't do. At the moment I do not have a primary need for it in the lib. However if you are still interested and you would like to open a PR we may can work together to make it happens. Thank you.
